name = "Thrase"
uuid = "3917ca59-4720-457e-a139-9f815f130244"
version = "0.1.0"
authors = ["Brittany A. Erickson"]

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshGrid = "ebf956a0-ef5e-43be-9fb1-27952996e635"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
Compat = "4.18.1"
DiffEqCallbacks = "4.8.0"
MeshGrid = "1.0.3"
Plots = "1.35.6"
PyPlot = "2.11.6"
UnicodePlots = "3.8.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
